// The canonical product/gallery category list, hand-written (not generated by
// dumpSeed.mjs — categories are admin-managed data, like src/seed/settings.mjs).
//
// This replaces the two hardcoded frontend arrays that used to disagree with
// each other: PRODUCT_CATS in admin/constants/admin.tsx and GALLERY_CATS in the
// same file, plus a third copy inside GalleryPage.tsx. Products and gallery
// items now share ONE list, because products are also shown in the gallery and
// gallery-only images carry a category of their own (e.g. "Printing").
//
// Everything a visitor sees as a filter pill comes from here. Deleting a
// category in the admin does NOT delete the products using it — it clears their
// `cat`, and they show up as "Uncategorized".

import { CategoryModel } from "../admin/categories/model.js";

export const SEED_CATEGORIES = [
  "Crystal",
  "Trophies",
  "Plaques",
  "Medals",
  "Collection",
  "Gifts",
  "Crystal Awards",
  "Printing",
];

/**
 * Insert any category that isn't there yet, in list order. Never destructive:
 * a rerun adds nothing and removes nothing, so it is safe to call from migrate.mjs
 * even against a database the admin has been editing by hand. Existing
 * categories keep their admin-arranged `order` — this never reorders or renames.
 *
 * @returns {Promise<{ added: string[], existing: string[] }>}
 */
export async function upsertCategories(names = SEED_CATEGORIES) {
  const found = await CategoryModel.find().select("name order").lean();
  const have = new Map(found.map((doc) => [doc.name.toLowerCase(), doc]));
  const missing = names.filter((name) => !have.has(name.toLowerCase()));

  if (missing.length === 0) {
    return { added: [], existing: found.map((doc) => doc.name) };
  }

  // `order` is countDocuments()-based at runtime, so a fresh list lands 0..n-1.
  // Only re-seeded names are numbered here, continuing after the highest order
  // already in use so a rerun never reshuffles the admin's arrangement.
  let next = found.length ? Math.max(...found.map((doc) => doc.order ?? 0)) + 1 : 0;

  await CategoryModel.insertMany(
    missing.map((name) => ({ name, order: next++ })),
    { ordered: false }
  );

  return {
    added: missing,
    existing: found.map((doc) => doc.name),
  };
}
