// AUTO-GENERATED by dumpSeed.mjs — do not edit by hand.
//
// This is the canonical seed content for the public website. It originally lived
// as hardcoded arrays in the frontend (data/products.ts, the galleryItems array
// in GalleryPage.tsx, the testimonials array in homeTestimonials.tsx). Those were
// replaced by database reads, so the content now lives here and is loaded into
// MongoDB by migrate.mjs. Images are read from ../Crystal Digital FrontEnd/src/imports.

export const SEED_PRODUCTS = [
  {
    "sourceImage": "image-2",
    "name": "Crystal Award",
    "desc": "Elegant personalized crystal awards for achievements and milestones.",
    "fullDesc": "Our premium Crystal Awards are crafted from optical-grade clarity crystal, delivering a stunning visual presence at any recognition ceremony. Each piece is meticulously polished and laser-engraved with precision, ensuring your message, logo, or design is captured with breathtaking detail. Perfect for corporate excellence awards, academic achievements, retirement gifts, and milestone celebrations.",
    "cat": "Crystal",
    "features": [
      "Optical-grade crystal clarity",
      "Precision 2D/3D laser engraving",
      "Custom text & logo engraving",
      "Presented in premium gift box",
      "Available in multiple sizes",
      "Certificate of authenticity included"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Optical Crystal Glass",
        "_id": "6ab81e48f5b0c25b6ad8324e"
      },
      {
        "label": "Finish",
        "value": "Hand-polished, glossy",
        "_id": "6ab81e48f5b0c25b6ad8324f"
      },
      {
        "label": "Sizes Available",
        "value": "Small (15cm), Medium (20cm), Large (25cm)",
        "_id": "6ab81e48f5b0c25b6ad83250"
      },
      {
        "label": "Engraving Type",
        "value": "Laser 2D / 3D engraving",
        "_id": "6ab81e48f5b0c25b6ad83251"
      },
      {
        "label": "Turnaround",
        "value": "3–5 business days",
        "_id": "6ab81e48f5b0c25b6ad83252"
      },
      {
        "label": "Packaging",
        "value": "Premium velvet gift box",
        "_id": "6ab81e48f5b0c25b6ad83253"
      }
    ],
    "customizable": [
      "Recipient's name & designation",
      "Company or school logo",
      "Custom message up to 150 words",
      "Achievement date",
      "Award title & category"
    ],
    "tags": [
      "Best Seller",
      "Premium"
    ],
    "sizes": [
      "Small — 15cm",
      "Medium — 20cm",
      "Large — 25cm"
    ],
    "slug": "crystal-award"
  },
  {
    "sourceImage": "image-1",
    "name": "Wooden Plaque",
    "desc": "Premium wooden plaques with gold-tone frame — ideal for recognition.",
    "fullDesc": "Our Wooden Plaques combine natural hardwood warmth with professional gold-tone framing to create a lasting recognition piece. The smooth wood surface is laser-engraved to produce crisp, readable text and detailed logos. Ideal for employee of the month awards, academic excellence certificates, community service recognition, and special occasion gifting.",
    "cat": "Plaques",
    "features": [
      "Premium hardwood construction",
      "Gold-tone metallic border frame",
      "High-contrast laser engraving",
      "Wall-mount ready with hardware",
      "Available in multiple wood finishes",
      "Eco-friendly and sustainably sourced"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Hardwood (Teak / Sheesham)",
        "_id": "6ab81e4cf5b0c25b6ad83255"
      },
      {
        "label": "Frame",
        "value": "Gold-tone metallic border",
        "_id": "6ab81e4cf5b0c25b6ad83256"
      },
      {
        "label": "Sizes Available",
        "value": "A5, A4, A3",
        "_id": "6ab81e4cf5b0c25b6ad83257"
      },
      {
        "label": "Engraving Type",
        "value": "Laser engraving / UV print",
        "_id": "6ab81e4cf5b0c25b6ad83258"
      },
      {
        "label": "Turnaround",
        "value": "2–4 business days",
        "_id": "6ab81e4cf5b0c25b6ad83259"
      },
      {
        "label": "Mounting",
        "value": "Wall-mount hook included",
        "_id": "6ab81e4cf5b0c25b6ad8325a"
      }
    ],
    "customizable": [
      "Recipient name & title",
      "Logo & badge printing",
      "Custom message or citation",
      "Date and event details",
      "Colour-fill engraving"
    ],
    "tags": [
      "Popular"
    ],
    "sizes": [
      "A5 — 21×15cm",
      "A4 — 30×21cm",
      "A3 — 42×30cm"
    ],
    "slug": "wooden-plaque"
  },
  {
    "sourceImage": "image-4",
    "name": "Gold Trophy",
    "desc": "Classic gold trophies for sports and corporate events.",
    "fullDesc": "Our Gold Trophies are the quintessential symbol of victory and excellence. Cast from high-quality metal alloys and finished with a brilliant gold plating, these trophies are designed to stand the test of time. Whether for sports tournaments, inter-school competitions, corporate awards, or cultural events, our gold trophies make every winner feel truly special.",
    "cat": "Trophies",
    "features": [
      "Bright gold-plated finish",
      "Heavy-weight metal construction",
      "Customizable figurine toppers",
      "Engraved name plate included",
      "Stable anti-tip weighted base",
      "Available from 6 inches to 36 inches"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Zinc alloy / Metal composite",
        "_id": "6ab81e50f5b0c25b6ad8325c"
      },
      {
        "label": "Finish",
        "value": "Gold electroplating",
        "_id": "6ab81e50f5b0c25b6ad8325d"
      },
      {
        "label": "Heights Available",
        "value": "15cm – 90cm",
        "_id": "6ab81e50f5b0c25b6ad8325e"
      },
      {
        "label": "Base",
        "value": "Marble / wood base option",
        "_id": "6ab81e50f5b0c25b6ad8325f"
      },
      {
        "label": "Name Plate",
        "value": "Engraved brass plate",
        "_id": "6ab81e50f5b0c25b6ad83260"
      },
      {
        "label": "Turnaround",
        "value": "1–3 business days",
        "_id": "6ab81e50f5b0c25b6ad83261"
      }
    ],
    "customizable": [
      "Trophy height and design style",
      "Name plate text & event details",
      "Topper style (sport, academic, cultural)",
      "Base material (wood, marble, acrylic)",
      "Ribbon or medal add-on"
    ],
    "tags": [
      "Most Popular"
    ],
    "sizes": [
      "15cm",
      "20cm",
      "25cm",
      "30cm",
      "45cm",
      "60cm",
      "75cm",
      "90cm"
    ],
    "slug": "gold-trophy"
  },
  {
    "sourceImage": "image-5",
    "name": "Cultural Trophy",
    "desc": "Handcrafted wooden temple-style trophies for cultural celebrations.",
    "fullDesc": "Our Cultural Trophies pay homage to Nepal's rich architectural and artistic heritage. Handcrafted by skilled artisans, these temple-style wooden trophies are finished with intricate detailing that reflects traditional craftsmanship. Ideal for cultural festivals, folk performances, religious events, and heritage celebrations across Nepal.",
    "cat": "Trophies",
    "features": [
      "Handcrafted by skilled artisans",
      "Intricate traditional detailing",
      "Natural wood with lacquer finish",
      "Unique Nepali cultural heritage design",
      "Laser-engraved name plate",
      "Sturdy and durable construction"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Solid wood (hand-carved)",
        "_id": "6ab81e56f5b0c25b6ad83263"
      },
      {
        "label": "Style",
        "value": "Temple / Pagoda architecture",
        "_id": "6ab81e56f5b0c25b6ad83264"
      },
      {
        "label": "Finish",
        "value": "Natural lacquer or painted",
        "_id": "6ab81e56f5b0c25b6ad83265"
      },
      {
        "label": "Heights Available",
        "value": "20cm – 60cm",
        "_id": "6ab81e56f5b0c25b6ad83266"
      },
      {
        "label": "Turnaround",
        "value": "3–7 business days",
        "_id": "6ab81e56f5b0c25b6ad83267"
      },
      {
        "label": "Engraving",
        "value": "Brass plate laser engraving",
        "_id": "6ab81e56f5b0c25b6ad83268"
      }
    ],
    "customizable": [
      "Carving style and motifs",
      "Wood type and colour",
      "Name plate inscription",
      "Size and height",
      "Cultural symbol or logo"
    ],
    "tags": [
      "Unique",
      "Handcrafted"
    ],
    "sizes": [
      "20cm",
      "30cm",
      "40cm",
      "50cm",
      "60cm"
    ],
    "slug": "cultural-trophy"
  },
  {
    "sourceImage": "image-3",
    "name": "Sports Medals Set",
    "desc": "Complete medal sets with ribbons for tournaments and competitions.",
    "fullDesc": "Our Sports Medals Sets are designed for every competitive event — from local school sports days to national tournaments. Available in gold, silver, and bronze finishes, each medal is crafted with a polished metallic face, vibrant full-colour ribbon, and precision laser-engraved or UV-printed design. Order in bulk for cost-effective recognition at your next event.",
    "cat": "Medals",
    "features": [
      "Gold, silver & bronze finishes",
      "Full-colour custom ribbon included",
      "UV-printed or engraved design",
      "Bulk order discounts available",
      "Fast turnaround for event deadlines",
      "Velvet pouch packaging option"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Zinc alloy / Aluminium",
        "_id": "6ab81e5af5b0c25b6ad8326a"
      },
      {
        "label": "Finish",
        "value": "Gold, Silver, Bronze plating",
        "_id": "6ab81e5af5b0c25b6ad8326b"
      },
      {
        "label": "Diameter",
        "value": "50mm, 65mm, 75mm",
        "_id": "6ab81e5af5b0c25b6ad8326c"
      },
      {
        "label": "Ribbon",
        "value": "Custom colour, 18–22mm wide",
        "_id": "6ab81e5af5b0c25b6ad8326d"
      },
      {
        "label": "Minimum Order",
        "value": "10 pieces",
        "_id": "6ab81e5af5b0c25b6ad8326e"
      },
      {
        "label": "Turnaround",
        "value": "2–5 business days",
        "_id": "6ab81e5af5b0c25b6ad8326f"
      }
    ],
    "customizable": [
      "Event name and logo",
      "Position text (1st, 2nd, 3rd)",
      "Year and date",
      "Custom ribbon colour",
      "Back-side engraving"
    ],
    "tags": [
      "Bulk Orders",
      "Popular"
    ],
    "sizes": [
      "50mm Diameter",
      "65mm Diameter",
      "75mm Diameter"
    ],
    "slug": "sports-medals"
  },
  {
    "sourceImage": "image-6",
    "name": "Award Collection",
    "desc": "Explore our full range of customized awards, gifts, and mementos.",
    "fullDesc": "Our Award Collection showcases the complete range of what Crystal Digital Art & Award House offers — from elegant crystal pieces to classic trophies, precision-engraved plaques, corporate branding items, and personalized gifts. Each item in our collection can be fully customized to match your event's theme, brand identity, or personal touch.",
    "cat": "Collection",
    "features": [
      "Complete range under one roof",
      "Free custom design consultation",
      "Corporate and bulk pricing",
      "Full-colour printing available",
      "Packaging and delivery options",
      "Sample viewing at our store"
    ],
    "specs": [
      {
        "label": "Product Range",
        "value": "Awards, Trophies, Plaques, Medals, Gifts",
        "_id": "6ab81e62f5b0c25b6ad83271"
      },
      {
        "label": "Customization",
        "value": "Full custom design support",
        "_id": "6ab81e62f5b0c25b6ad83272"
      },
      {
        "label": "Minimum Order",
        "value": "1 piece (no minimum)",
        "_id": "6ab81e62f5b0c25b6ad83273"
      },
      {
        "label": "Bulk Discount",
        "value": "Available for 10+ orders",
        "_id": "6ab81e62f5b0c25b6ad83274"
      },
      {
        "label": "Consultation",
        "value": "Free design consultation",
        "_id": "6ab81e62f5b0c25b6ad83275"
      },
      {
        "label": "Turnaround",
        "value": "Varies by product",
        "_id": "6ab81e62f5b0c25b6ad83276"
      }
    ],
    "customizable": [
      "Any text, name, or message",
      "Logo and brand identity",
      "Colour and material",
      "Size and quantity",
      "Gift wrapping and packaging"
    ],
    "tags": [
      "Full Range"
    ],
    "sizes": [
      "Custom — varies by product"
    ],
    "slug": "award-collection"
  },
  {
    "sourceImage": "image-9",
    "name": "Sports Trophy Sets",
    "desc": "Complete coordinated sets for tournaments & competitions.",
    "fullDesc": "Our Sports Trophy Sets provide everything you need to recognize excellence at your tournament or sporting event. Each set includes coordinated trophies in multiple sizes for different podium positions, ensuring a unified and professional look. Available in various sport-specific designs including football, cricket, volleyball, badminton, and more.",
    "cat": "Trophies",
    "features": [
      "Coordinated multi-size trophy set",
      "Sport-specific figurine toppers",
      "Matching ribbon medals option",
      "Gold, silver, bronze finishes",
      "Engraved base plates included",
      "Event-ready fast turnaround"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Metal composite / Zinc alloy",
        "_id": "6ab81e67f5b0c25b6ad83278"
      },
      {
        "label": "Set Composition",
        "value": "1st, 2nd, 3rd + participation",
        "_id": "6ab81e67f5b0c25b6ad83279"
      },
      {
        "label": "Sports Designs",
        "value": "Cricket, Football, Volleyball & more",
        "_id": "6ab81e67f5b0c25b6ad8327a"
      },
      {
        "label": "Sizes",
        "value": "20cm – 60cm per tier",
        "_id": "6ab81e67f5b0c25b6ad8327b"
      },
      {
        "label": "Turnaround",
        "value": "1–3 business days",
        "_id": "6ab81e67f5b0c25b6ad8327c"
      },
      {
        "label": "Add-ons",
        "value": "Medals, certificates, ribbons",
        "_id": "6ab81e67f5b0c25b6ad8327d"
      }
    ],
    "customizable": [
      "Sport type and figurine design",
      "Name plate text",
      "Number of positions in set",
      "Base style and material",
      "Matching medal set add-on"
    ],
    "tags": [
      "Sets",
      "Events"
    ],
    "sizes": [
      "20cm Set",
      "30cm Set",
      "40cm Set",
      "50cm Set",
      "60cm Set"
    ],
    "slug": "sports-trophy-sets"
  },
  {
    "sourceImage": "image-10",
    "name": "Gold Honour Trophy",
    "desc": "Classic gold trophies for felicitation events.",
    "fullDesc": "The Gold Honour Trophy is our signature felicitation piece — a timeless symbol of respect and recognition. Designed for formal ceremonies, retirement events, lifetime achievement awards, and VIP presentations, this trophy commands attention with its commanding height, brilliant gold finish, and premium engraved base plate.",
    "cat": "Trophies",
    "features": [
      "Commanding ceremonial height",
      "Brilliant gold-plated finish",
      "Premium engraved brass plate",
      "Heavy marble or rosewood base",
      "Velvet-lined gift box packaging",
      "Ideal for formal felicitation"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Metal with gold plating",
        "_id": "6ab81e6bf5b0c25b6ad8327f"
      },
      {
        "label": "Base",
        "value": "Premium marble or rosewood",
        "_id": "6ab81e6bf5b0c25b6ad83280"
      },
      {
        "label": "Heights Available",
        "value": "30cm – 75cm",
        "_id": "6ab81e6bf5b0c25b6ad83281"
      },
      {
        "label": "Name Plate",
        "value": "Engraved brass / gold plate",
        "_id": "6ab81e6bf5b0c25b6ad83282"
      },
      {
        "label": "Packaging",
        "value": "Velvet-lined gift box",
        "_id": "6ab81e6bf5b0c25b6ad83283"
      },
      {
        "label": "Turnaround",
        "value": "2–4 business days",
        "_id": "6ab81e6bf5b0c25b6ad83284"
      }
    ],
    "customizable": [
      "Height and design style",
      "Engraved name and title",
      "Base material and colour",
      "Personal message inscription",
      "Logo or emblem on body"
    ],
    "tags": [
      "Premium",
      "Formal"
    ],
    "sizes": [
      "30cm",
      "45cm",
      "60cm",
      "75cm"
    ],
    "slug": "gold-honour-trophy"
  },
  {
    "sourceImage": "image-11",
    "name": "Cultural & Heritage Trophy",
    "desc": "Handcrafted wooden temple-style awards for cultural events.",
    "fullDesc": "Celebrating Nepal's diverse cultural legacy, our Heritage Trophies are masterpieces of woodcraft and artistry. Inspired by the pagoda temples of the Kathmandu Valley and folk art traditions of Gandaki Province, each trophy is individually handcrafted, making it a one-of-a-kind collector's piece. Perfect for cultural events, folk festivals, and heritage preservation awards.",
    "cat": "Trophies",
    "features": [
      "Individually handcrafted by artisans",
      "Inspired by Nepali pagoda architecture",
      "Rich wood grain and lacquer finish",
      "Traditional motifs and carvings",
      "Unique — no two pieces identical",
      "Artisan-made locally in Nepal"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Sal wood / Teak (hand-carved)",
        "_id": "6ab81e70f5b0c25b6ad83286"
      },
      {
        "label": "Style",
        "value": "Multi-tiered pagoda design",
        "_id": "6ab81e70f5b0c25b6ad83287"
      },
      {
        "label": "Finish",
        "value": "Natural wood, lacquer, gold accents",
        "_id": "6ab81e70f5b0c25b6ad83288"
      },
      {
        "label": "Heights",
        "value": "25cm – 70cm",
        "_id": "6ab81e70f5b0c25b6ad83289"
      },
      {
        "label": "Turnaround",
        "value": "5–10 business days",
        "_id": "6ab81e70f5b0c25b6ad8328a"
      },
      {
        "label": "Authenticity",
        "value": "Handmade certificate included",
        "_id": "6ab81e70f5b0c25b6ad8328b"
      }
    ],
    "customizable": [
      "Carving depth and motifs",
      "Colour scheme and paint",
      "Inscription plate text",
      "Tier count and height",
      "Cultural symbol integration"
    ],
    "tags": [
      "Handmade",
      "Heritage"
    ],
    "sizes": [
      "25cm",
      "35cm",
      "45cm",
      "55cm",
      "70cm"
    ],
    "slug": "cultural-heritage-trophy"
  },
  {
    "sourceImage": "image-12",
    "name": "Premium Display Trophy",
    "desc": "Showcase-ready trophies for offices and lobbies.",
    "fullDesc": "Our Premium Display Trophies are designed for maximum visual impact — ideal for permanent display in offices, boardrooms, halls of fame, and institution lobbies. Each piece combines polished metal with crystal elements, mounted on a premium base, and optionally enclosed in a custom glass display case for preservation and prestige.",
    "cat": "Trophies",
    "features": [
      "Optional custom glass display case",
      "Crystal and metal combination",
      "LED-illuminated base option",
      "Permanent office display quality",
      "Weather-resistant finish",
      "Custom branding on case"
    ],
    "specs": [
      {
        "label": "Material",
        "value": "Metal + crystal elements",
        "_id": "6ab81e74f5b0c25b6ad8328d"
      },
      {
        "label": "Display Case",
        "value": "Optional custom glass case",
        "_id": "6ab81e74f5b0c25b6ad8328e"
      },
      {
        "label": "Base",
        "value": "Illuminated LED base option",
        "_id": "6ab81e74f5b0c25b6ad8328f"
      },
      {
        "label": "Heights",
        "value": "35cm – 80cm",
        "_id": "6ab81e74f5b0c25b6ad83290"
      },
      {
        "label": "Turnaround",
        "value": "5–7 business days",
        "_id": "6ab81e74f5b0c25b6ad83291"
      },
      {
        "label": "Warranty",
        "value": "Lifetime quality guarantee",
        "_id": "6ab81e74f5b0c25b6ad83292"
      }
    ],
    "customizable": [
      "Trophy height and shape",
      "Crystal colour and cut style",
      "Engraved name plate",
      "Base lighting option",
      "Glass case dimensions"
    ],
    "tags": [
      "Luxury",
      "Display"
    ],
    "sizes": [
      "35cm",
      "45cm",
      "60cm",
      "70cm",
      "80cm"
    ],
    "slug": "premium-display-trophy"
  }
];

export const SEED_GALLERY = [
  {
    "sourceImage": "image-2",
    "label": "Token of Appreciation Award",
    "cat": "Crystal Awards",
    "linkedProductId": "crystal-award"
  },
  {
    "sourceImage": "image-1",
    "label": "Wooden Plaque with Gold Frame",
    "cat": "Plaques",
    "linkedProductId": "wooden-plaque"
  },
  {
    "sourceImage": "image-4",
    "label": "Gold Sports Trophy",
    "cat": "Trophies",
    "linkedProductId": "gold-trophy"
  },
  {
    "sourceImage": "image-5",
    "label": "Cultural Temple Trophy",
    "cat": "Trophies",
    "linkedProductId": "cultural-trophy"
  },
  {
    "sourceImage": "image-3",
    "label": "Sports Medal Set",
    "cat": "Medals",
    "linkedProductId": "sports-medals"
  },
  {
    "sourceImage": "image-6",
    "label": "Full Award Collection Display",
    "cat": "Collection",
    "linkedProductId": "award-collection"
  },
  {
    "sourceImage": "image-7",
    "label": "Awards & Trophies Showcase",
    "cat": "Collection",
    "linkedProductId": ""
  },
  {
    "sourceImage": "image-8",
    "label": "Trophy & Plaque Inventory",
    "cat": "Collection",
    "linkedProductId": ""
  },
  {
    "sourceImage": "image-9",
    "label": "Store Interior — Award Shelf Display",
    "cat": "Collection",
    "linkedProductId": ""
  }
];

export const SEED_TESTIMONIALS = [
  {
    "sourceImage": "",
    "name": "Ramesh Sharma",
    "company": "Pokhara Academy",
    "text": "Crystal Digital delivered outstanding trophies for our annual sports day. The quality was beyond expectations and delivery was on time!",
    "rating": 5
  },
  {
    "sourceImage": "",
    "name": "Sunita Gurung",
    "company": "Annapurna Hotels",
    "text": "We ordered custom crystal awards for our employee recognition ceremony. Beautifully crafted and professionally packaged. Highly recommend!",
    "rating": 5
  },
  {
    "sourceImage": "",
    "name": "Bikash Thapa",
    "company": "Gandaki Province Office",
    "text": "Excellent service for our government felicitation event. The wooden plaques and laser engraving were top-notch. Will definitely order again.",
    "rating": 5
  }
];
