// `npm run seed:dump` — regenerates src/seed/data.mjs from the live database,
// the reverse of migrate.mjs. The only write in the run is that one file.

import "dotenv/config";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";
import mongoose from "mongoose";

import { ProductModel } from "./src/admin/products/model.js";
import { GalleryModel } from "./src/admin/gallery/model.js";
import { TestimonialModel } from "./src/admin/testimonials/model.js";

const HERE = dirname(fileURLToPath(import.meta.url));

await mongoose.connect(process.env.MONGO_DB_URI, { serverSelectionTimeoutMS: 15000 });

const products = await ProductModel.find({ slug: { $exists: true } })
  .sort({ createdAt: 1 })
  .lean();
const gallery = await GalleryModel.find().sort({ createdAt: 1 }).lean();
const testimonials = await TestimonialModel.find().sort({ createdAt: 1 }).lean();

// The Cloudinary publicId ends in the original local filename
// (crystal-digital/products/image-2.png -> image-2.png). Keeping it as
// sourceImage means a re-seed re-uploads the right file without any
// hand-maintained mapping table.
const basename = (publicId = "") => publicId.split("/").pop() ?? "";

const strip = (doc) => {
  const {
    _id,
    __v,
    createdAt,
    updatedAt,
    imgUrl,
    imgPublicId,
    ...rest
  } = doc;
  return { sourceImage: basename(imgPublicId), ...rest };
};

const body = `// AUTO-GENERATED by dumpSeed.mjs — do not edit by hand.
//
// This is the canonical seed content for the public website. It originally lived
// as hardcoded arrays in the frontend (data/products.ts, the galleryItems array
// in GalleryPage.tsx, the testimonials array in homeTestimonials.tsx). Those were
// replaced by database reads, so the content now lives here and is loaded into
// MongoDB by migrate.mjs. Images are read from ../Crystal Digital FrontEnd/src/imports.

export const SEED_PRODUCTS = ${JSON.stringify(products.map(strip), null, 2)};

export const SEED_GALLERY = ${JSON.stringify(gallery.map(strip), null, 2)};

export const SEED_TESTIMONIALS = ${JSON.stringify(testimonials.map(strip), null, 2)};
`;

writeFileSync(resolve(HERE, "src/seed/data.mjs"), body);
console.log(
  `Wrote src/seed/data.mjs — ${products.length} products, ${gallery.length} gallery items, ${testimonials.length} testimonials`
);
await mongoose.disconnect();
